title: JavaFullDev
description: Java, Kotlin, Spring, Angular, DevOps.

baseurl: /
color-scheme: "#05ABD5" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
